- name: Check installed version of vim
  command: "vim --version | grep {{ item }}"
  ignore_errors: true
  register: vim_installed
  changed_when: vim_installed|failed
  with_items:
    - +clipboard
    - +lua
    - +perl
    - +python
    - +ruby

- include: install_vim.yml
  when: vim_installed|failed
