---
- name: Install rbenv plugins
  git: repo='https://github.com/{{ item.repo }}.git' dest='~/.rbenv/plugins/{{ item.dest }}' accept_hostkey=yes
  with_items:
    - { repo: 'sstephenson/rbenv-vars', dest: 'rbenv-vars' }
    - { repo: 'sstephenson/ruby-build', dest: 'ruby-build' }
    - { repo: 'sstephenson/rbenv-default-gems', dest: 'rbenv-default-gems' }
    - { repo: 'sstephenson/rbenv-gem-rehash', dest: 'rbenv-gem-rehash' }
    - { repo: 'rkh/rbenv-update', dest: 'rbenv-update' }
    - { repo: 'garnieretienne/rvm-download', dest: 'rvm-download' }

- name: Check if ruby "{{ ruby.version }}" is installed
  shell: "rbenv versions | grep {{ ruby.version }}"
  register: ruby_installed
  changed_when: ruby_installed|failed
  ignore_errors: true
  sudo: no


- name: Install ruby {{ ruby.version }}
  command: rbenv install {{ ruby.version }}
  when: ruby_installed|failed
  sudo: no
